apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - path: bundestagio-depl.yaml
  - path: bundestagio-admin-depl.yaml
  - path: democracy-api-depl.yaml
  - path: democracy-app-depl.yaml
  - path: mongo-statefulset.yaml

resources:
  - ../../../base/cluster
  - ingress-srv.yaml

namespace: democracy-production
