apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../main
  - mongo-headless-service.yaml
  - mongo-statefulset.yaml

patches:
  - path: patches/bundestagio-admin-depl.yaml
  - path: patches/bundestagio-depl.yaml
  - path: patches/democracy-api-depl.yaml
  - path: patches/democracy-app-depl.yaml
