apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/cluster
  - ingress-srv.yaml

patches:
  - path: bundestagio-depl.yaml
  - path: bundestagio-admin-depl.yaml
  - path: democracy-api-depl.yaml
  - path: democracy-app-depl.yaml
  - path: import-conference-week-details.yaml
  - path: import-deputy-profiles.yaml
  - path: import-named-poll-deputies.yaml
  - path: import-named-polls.yaml
  - path: import-procedures.yaml
  - path: mongo-statefulset.yaml

namespace: democracy-internal
