apiVersion: apps/v1
kind: Deployment
metadata:
  name: bundestagio-admin-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bundestagio-admin
  template:
    metadata:
      labels:
        app: bundestagio-admin
    spec:
      containers:
        - name: bundestagio-admin
          image: democracy/bundestag.io-admin:3.2.0
          env:
            - name: AI_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ai-votes-access-token
                  key: ACCESS_TOKEN
                  optional: false
          envFrom:
            - configMapRef:
                name: bio-admin-config
            - secretRef:
                name: bio-admin-login
            - secretRef:
                name: bundestag-result-edit-token
          resources:
            limits:
              memory: "200M"
              cpu: "100m"
            requests:
              memory: "100M"
              cpu: "30m"
---
apiVersion: v1
kind: Service
metadata:
  name: bundestagio-admin-srv
spec:
  selector:
    app: bundestagio-admin
  ports:
    - name: bundestagio-admin
      protocol: TCP
      port: 3000
      targetPort: 3000
