apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-procedures-cronjob
spec:
  schedule: '0 1 * * *'
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 43200
          containers:
            - name: import-procedures
              image: democracy/crawler:pr-520
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: crawler-config
