apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-named-polls-cronjob
spec:
  schedule: '15 1 * * *'
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: import-named-polls
              image: democracy/import-named-polls:pr-504
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: bio-api-config
                      key: DB_URL
