apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-procedures-cronjob
spec:
  schedule: "0 1 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 86400
          containers:
            - name: import-procedures
              image: democracy/crawler:1.1.6
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: crawler-config
                - secretRef:
                    name: dip-api-token
                    optional: false
