apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-named-poll-deputies-cronjob
spec:
  schedule: '45 1 * * *'
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: import-named-poll-deputies
              image: democracy/import-named-poll-deputies:pr-504
              imagePullPolicy: Always
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: bio-api-config
                      key: DB_URL
