apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-deputy-profiles-cronjob
spec:
  schedule: '0 4 * * *'
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 43200
          containers:
            - name: import-deputy-profiles
              image: democracy/import-deputy-profiles:pr-502
              imagePullPolicy: Always
              env:
                - name: PERIOD
                  value: '20'
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: bio-api-config
                      key: DB_URL
