apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-plenary-minutes-cronjob
spec:
  schedule: "15 1 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 86400
          containers:
            - name: import-plenary-minutes
              image: democracy/import-plenary-minutes:0.1.19
              imagePullPolicy: Always
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: bio-api-config
                      key: DB_URL
