apiVersion: batch/v1
kind: CronJob
metadata:
  name: index-sync-bundestagio-cronjob
spec:
  schedule: '0 7 * * *'
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 43200
          containers:
            - name: index-sync-bundestagio
              image: democracy/index-sync-bundestagio:pr-520
              imagePullPolicy: Always
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: bio-api-config
                      key: DB_URL
