apiVersion: batch/v1
kind: CronJob
metadata:
  name: shedule-bio-resync-cronjob
spec:
  schedule: '55 2 * */1 *'
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 43200
          containers:
            - name: shedule-bio-resync
              image: democracy/shedule-bio-resync:0.1.5
              imagePullPolicy: Always
              env:
                - name: DB_URL
                  valueFrom:
                    configMapKeyRef:
                      name: democracy-api-config
                      key: DB_URL
