name: infrastructure-base
description: Base infrastructure for democracy platform (domains, VPCs, firewalls)
runtime:
  name: nodejs
  options:
    packagemanager: pnpm
    typescript: false
    binary: tsx
main: src/
